language: java

sudo: false   # Linux OS: run in container

env:
  global:
    # get all the branches referencing this commit
    - TAG_BRANCH=$(git ls-remote origin | sed -n "\|$TRAVIS_COMMIT\s\+refs/heads/|{s///p}")
    - TERM=dumb

# Necessary environment variables on Travis CI:
#
# GITHUB_TOKEN: Token from here: https://github.com/settings/tokens => with scope "public_repo"
# BINTRAY_USER: Bintray username
# BINTRAY_API_KEY: API key from here: https://bintray.com/profile/edit => API Key
#
# The Bintray URL follows the following pattern: https://bintray.com/subject/repo/package
# BINTRAY_SUBJECT=subject
# BINTRAY_REPO=repo
# BINTRAY_PACKAGE=package

jdk: openjdk11

addons:
  apt:
    packages:
      - p7zip-full

install: true

cache:
  directories:
    - $HOME/.m2

script: mvn test -B

after_success:
  - chmod +x .github/deploy_prepare.sh
  - chmod +x .github/deploy_bintray_central.sh

deploy:
  - provider: script
    script: .github/deploy_prepare.sh
    skip_cleanup: true
    on: &on
      repo: $TRAVIS_REPO_SLUG
      tags: true
      all_branches: true
      condition: $TAG_BRANCH =~ ^(master|master-11)$
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - javadoc.zip
      - /**/target/*.jar
    skip_cleanup: true
    name: Release $TRAVIS_TAG
    body: See [CHANGELOG.md](https://github.com/$TRAVIS_REPO_SLUG/blob/$TAG_BRANCH/CHANGELOG.md)
    on: *on
  - provider: script
    script: .github/deploy_bintray_central.sh
    skip_cleanup: true
    on: *on
